export enum ActionTypes {
    ADD_TIME_ZONE = 'ADD_TIME_ZONE',
    DELETE_TIME_ZONE = 'DELETE_TIME_ZONE',
    CHANGE_DATE = 'CHANGE_DATE',
    CHANGE_THEME = 'CHANGE_THEME',
    REVERSE_TIME_ZONES = 'REVERSE_TIME_ZONES',
    CHANGE_TIME = 'CHANGE_TIME',
    CHANGE_ORDER = 'CHANGE_ORDER',
  }